# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_3/design_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_mux_0_0/design_3_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_mux_0_0 || ORIG_REF_NAME==design_3_mux_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_display_decoder_0_0/design_3_display_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_display_decoder_0_0 || ORIG_REF_NAME==design_3_display_decoder_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_decoder_0_0/design_3_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_decoder_0_0 || ORIG_REF_NAME==design_3_decoder_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_decimal_counter_0_0/design_3_decimal_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_decimal_counter_0_0 || ORIG_REF_NAME==design_3_decimal_counter_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_clock_divider_0_0/design_3_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_clock_divider_0_0 || ORIG_REF_NAME==design_3_clock_divider_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_clock_divider_1_0/design_3_clock_divider_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_clock_divider_1_0 || ORIG_REF_NAME==design_3_clock_divider_1_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xlconstant_0_0/design_3_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_xlconstant_0_0 || ORIG_REF_NAME==design_3_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xlconstant_1_0/design_3_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_xlconstant_1_0 || ORIG_REF_NAME==design_3_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_counter_0_0/design_3_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_counter_0_0 || ORIG_REF_NAME==design_3_counter_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_counter_1_0/design_3_counter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_counter_1_0 || ORIG_REF_NAME==design_3_counter_1_0} -quiet] -quiet

# XDC: c:/xproj/project_8.5/project_8.5.gen/sources_1/bd/design_3/design_3_ooc.xdc
