# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_seg_decoder_0_0/design_1_seg_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_seg_decoder_0_0 || ORIG_REF_NAME==design_1_seg_decoder_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux4_1_0_0/design_1_mux4_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux4_1_0_0 || ORIG_REF_NAME==design_1_mux4_1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_0/design_1_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_0 || ORIG_REF_NAME==design_1_xlslice_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_0/design_1_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_0 || ORIG_REF_NAME==design_1_xlslice_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clkdiv_0_0/design_1_clkdiv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clkdiv_0_0 || ORIG_REF_NAME==design_1_clkdiv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_counter_0_0/design_1_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_counter_0_0 || ORIG_REF_NAME==design_1_counter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_encoder2_4_0_0/design_1_encoder2_4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_encoder2_4_0_0 || ORIG_REF_NAME==design_1_encoder2_4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CLA_4bit_0_0/design_1_CLA_4bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CLA_4bit_0_0 || ORIG_REF_NAME==design_1_CLA_4bit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_concatmodule_0_1/design_1_concatmodule_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_concatmodule_0_1 || ORIG_REF_NAME==design_1_concatmodule_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_split_digit_0_0/design_1_split_digit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_split_digit_0_0 || ORIG_REF_NAME==design_1_split_digit_0_0} -quiet] -quiet

# XDC: c:/xproj/project_9.1E1/project_9.1E1.gen/sources_1/bd/design_1/design_1_ooc.xdc
