# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_PISO_0_2/design_2_PISO_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_PISO_0_2 || ORIG_REF_NAME==design_2_PISO_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_PISO_1_1/design_2_PISO_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_PISO_1_1 || ORIG_REF_NAME==design_2_PISO_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clock_divider_0_0/design_2_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clock_divider_0_0 || ORIG_REF_NAME==design_2_clock_divider_0_0} -quiet] -quiet

# XDC: c:/xproj/project_7.5/project_7.5.gen/sources_1/bd/design_2/design_2_ooc.xdc
