# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/displaycontrollerE1/displaycontrollerE1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1 || ORIG_REF_NAME==displaycontrollerE1} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_bin2bcd_0_0/displaycontrollerE1_bin2bcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_bin2bcd_0_0 || ORIG_REF_NAME==displaycontrollerE1_bin2bcd_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_mux_0_0/displaycontrollerE1_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_mux_0_0 || ORIG_REF_NAME==displaycontrollerE1_mux_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_display_decoder_0_0/displaycontrollerE1_display_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_display_decoder_0_0 || ORIG_REF_NAME==displaycontrollerE1_display_decoder_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_counter_0_0/displaycontrollerE1_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_counter_0_0 || ORIG_REF_NAME==displaycontrollerE1_counter_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_decoder_0_0/displaycontrollerE1_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_decoder_0_0 || ORIG_REF_NAME==displaycontrollerE1_decoder_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_0/displaycontrollerE1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_0 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_1/displaycontrollerE1_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_1 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_1} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_2/displaycontrollerE1_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_2 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_2} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_3/displaycontrollerE1_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_3 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_3} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_clock_divider_0_0/displaycontrollerE1_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_clock_divider_0_0 || ORIG_REF_NAME==displaycontrollerE1_clock_divider_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlconstant_0_0/displaycontrollerE1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlconstant_0_0 || ORIG_REF_NAME==displaycontrollerE1_xlconstant_0_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_displaycontrollerE1_0_0/design_1_displaycontrollerE1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_displaycontrollerE1_0_0 || ORIG_REF_NAME==design_1_displaycontrollerE1_0_0} -quiet] -quiet

# Block Designs: bd/displaycontrollerE1/displaycontrollerE1.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1 || ORIG_REF_NAME==displaycontrollerE1} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_bin2bcd_0_0/displaycontrollerE1_bin2bcd_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_bin2bcd_0_0 || ORIG_REF_NAME==displaycontrollerE1_bin2bcd_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_mux_0_0/displaycontrollerE1_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_mux_0_0 || ORIG_REF_NAME==displaycontrollerE1_mux_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_display_decoder_0_0/displaycontrollerE1_display_decoder_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_display_decoder_0_0 || ORIG_REF_NAME==displaycontrollerE1_display_decoder_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_counter_0_0/displaycontrollerE1_counter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_counter_0_0 || ORIG_REF_NAME==displaycontrollerE1_counter_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_decoder_0_0/displaycontrollerE1_decoder_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_decoder_0_0 || ORIG_REF_NAME==displaycontrollerE1_decoder_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_0/displaycontrollerE1_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_0 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_1/displaycontrollerE1_xlslice_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_1 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_1} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_2/displaycontrollerE1_xlslice_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_2 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_2} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlslice_0_3/displaycontrollerE1_xlslice_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlslice_0_3 || ORIG_REF_NAME==displaycontrollerE1_xlslice_0_3} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_clock_divider_0_0/displaycontrollerE1_clock_divider_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_clock_divider_0_0 || ORIG_REF_NAME==displaycontrollerE1_clock_divider_0_0} -quiet] -quiet

# IP: bd/displaycontrollerE1/ip/displaycontrollerE1_xlconstant_0_0/displaycontrollerE1_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==displaycontrollerE1_xlconstant_0_0 || ORIG_REF_NAME==displaycontrollerE1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_random_FSM_0_1/design_1_random_FSM_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_random_FSM_0_1 || ORIG_REF_NAME==design_1_random_FSM_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_divider_0_0/design_1_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clock_divider_0_0 || ORIG_REF_NAME==design_1_clock_divider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_divider_1_0/design_1_clock_divider_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clock_divider_1_0 || ORIG_REF_NAME==design_1_clock_divider_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# XDC: c:/xproj/project_12.2/project_12.2.gen/sources_1/bd/displaycontrollerE1/displaycontrollerE1_ooc.xdc

# XDC: c:/xproj/project_12.2/project_12.2.gen/sources_1/bd/displaycontrollerE1/displaycontrollerE1_ooc.xdc

# XDC: c:/xproj/project_12.2/project_12.2.gen/sources_1/bd/design_1/design_1_ooc.xdc
