# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/testcounter/testcounter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter || ORIG_REF_NAME==testcounter} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_counterE2_0_0/testcounter_counterE2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_counterE2_0_0 || ORIG_REF_NAME==testcounter_counterE2_0_0} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_mux_0_0/testcounter_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_mux_0_0 || ORIG_REF_NAME==testcounter_mux_0_0} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_display_decoder_0_0/testcounter_display_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_display_decoder_0_0 || ORIG_REF_NAME==testcounter_display_decoder_0_0} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_decoder_0_0/testcounter_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_decoder_0_0 || ORIG_REF_NAME==testcounter_decoder_0_0} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_counterE1R_0_0/testcounter_counterE1R_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_counterE1R_0_0 || ORIG_REF_NAME==testcounter_counterE1R_0_0} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_clock_divider_0_0/testcounter_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_clock_divider_0_0 || ORIG_REF_NAME==testcounter_clock_divider_0_0} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_xlconstant_1_0/testcounter_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_xlconstant_1_0 || ORIG_REF_NAME==testcounter_xlconstant_1_0} -quiet] -quiet

# IP: bd/testcounter/ip/testcounter_bin2bcd_0_0/testcounter_bin2bcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testcounter_bin2bcd_0_0 || ORIG_REF_NAME==testcounter_bin2bcd_0_0} -quiet] -quiet

# XDC: c:/xproj/project_12.2A1/project_12.2A1.gen/sources_1/bd/testcounter/testcounter_ooc.xdc
